version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/CumServer
    environment:
      JVM_OPTS: -Xmx3600M -Xms3600M -Xincgc -XX:+AggressiveOpts -XX:+UseCompressedOops -XX:+UseFastAccessorMethods
      TERM: dumb
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
    - run: chmod +x gradlew
    - run: ./gradlew build
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.m2
        - ~/.gradle
    - store_artifacts:
        path: ~/CumServer/build/libs
        destination: CumServer
